### ISSUE TITLE
Range selections

### ISSUE THREAD

**Issue by romulogoncalves** [NLeSC/3D_geospatial_risk_management#10]
There is an issue when the boundaries are not expressed using doubles/decimals. MonetDB does a bat.calc (lng) which takes in average 6 secs. 

Example:
x between 93816 and 93916 and
y between 463891 and 463991 and

should be

x between 93816.0 and 93916.0 and
y between 463891.0 and 463991.0 and

**Comment by romulogoncalves** [comment]
Request to fix it submitted.

**Comment by tomvantilburg** [comment]
Noticed same behaviour with:

> SELECT \* FROM ahn3 WHERE x > 90002.253 AND x < 90003 limit 10;

From the trace it shows as a bat.calc issue:
`34835432 | X_247=<tmp_1350>[86147162]:bat[:lng] := batcalc.lng(3:int,X_150=<tmp_1205>[86147162]:bat[:int],11:int,3:int);                                                                                                                 |
|  35227996 | X_254=<tmp_1534>[86147165]:bat[:lng] := batcalc.lng(3:int,X_157=<tmp_1533>[86147165]:bat[:int],11:int,3:int);                                                                                                                 |
|  35256152 | X_253=<tmp_1537>[86147162]:bat[:lng] := batcalc.lng(3:int,X_156=<tmp_1536>[86147162]:bat[:int],11:int,3:int);                                                                                                                 |
|  35892422 | X_252=<tmp_1454>[86147162]:bat[:lng] := batcalc.lng(3:int,X_155=<tmp_1466>[86147162]:bat[:int],11:int,3:int);                                                                                                                 |
|  36337919 | X_248=<tmp_1475>[86147162]:bat[:lng] := batcalc.lng(3:int,X_151=<tmp_1367>[86147162]:bat[:int],11:int,3:int);                                                                                                                 |
|        83 | X_138=<tmp_1457>[86147162]:bat[:oid] := sql.tid(X_3=0:int,"sys":str,"c30_fz1":str,1:int,8:int);                                                                                                                               |
|  40482024 | X_251=<tmp_1541>[86147162]:bat[:lng] := batcalc.lng(3:int,X_154=<tmp_1540>[86147162]:bat[:int],11:int,3:int);                                                                                                                 |
|  40452243 | X_259=<tmp_1532>[86127000]:bat[:oid] := algebra.thetasubselect(X_154=<tmp_1540>[86147162]:bat[:int],X_143=<tmp_1436>[86147162]:bat[:oid],X_11=90002253:int,">":str);                                                          |
|  20866071 | X_250=<tmp_1501>[86147162]:bat[:lng] := batcalc.lng(3:int,X_153=<tmp_1357>[86147162]:bat[:int],11:int,3:int);                                                                                                                 |
|        97 | X_140=<tmp_1502>[86147162]:bat[:oid] := sql.tid(X_3=0:int,"sys":str,"c30_fz1":str,2:int,8:int);                                                                                                                               |
|        47 | X_152=<tmp_1245>[86147162]:bat[:int] := sql.bind(X_3=0:int,"sys":str,"c30_fz1":str,"x":str,0:int,2:int,8:int);                                                                                                                |
|  19335912 | X_256=<tmp_1474>[86137875]:bat[:oid] := algebra.thetasubselect(X_151=<tmp_1367>[86147162]:bat[:int],X_138=<tmp_1457>[86147162]:bat[:oid],X_11=90002253:int,">":str);                                                          |
|  15600211 | X_258=<tmp_1544>[86126217]:bat[:oid] := algebra.thetasubselect(X_153=<tmp_1357>[86147162]:bat[:int],X_141=<tmp_1233>[86147162]:bat[:oid],X_11=90002253:int,">":str);                                                          |
|    109463 | X_266=<tmp_1233>[6939]:bat[:oid] := algebra.thetasubselect(X_250=<tmp_1501>[86147162]:bat[:lng],X_258=<tmp_1544>[86126217]:bat[:oid],X_10=90003000:lng,"<":str);`

**Comment by romulogoncalves** [comment]
Another issue related with this bug is the fact it is not able to perform partition elimination.
The same happens when using an arithmetic expression or simply cast the integer to a double.

**Comment by romulogoncalves** [comment]
Partition elimination is now properly working. The bat.calc issue is also solved.
