### ISSUE TITLE
ST_DumpPoints should include srid

### ISSUE THREAD

**Issue by tomvantilburg** [NLeSC/3D_geospatial_risk_management#15]
At the moment ST_DumpPoints will remove the SRID.

This might also be true for the other ST_Dump or exploding functions like ST_PointN.

**Comment by romulogoncalves** [comment]
It is invalid, maybe the geometry we passed did not have the SRID set. The following example shows it works:

declare _geom2 string;
set _geom2 = 'POLYGON ((93910.602 463934.263, 93914.44 463934.856, 93907.227 463933.742, 93910.602 463934.263))';

sql>select ST_SRID(polygonwkb) from ST_DUMP(ST_GeometryFromText(_geom2));
% .L1 # table_name
% st_srid_polygonwkb # name
% int # type
% 1 # length
[ 0 ]
sql>select ST_SRID(polygonwkb) from ST_DUMP(ST_SETSRID(ST_GeometryFromText(_geom2),28992));
% .L1 # table_name
% st_srid_polygonwkb # name
% int # type
% 5 # length
[ 28992 ]
sql>
