### ISSUE TITLE
Unable to specify alias with window functions

### ISSUE THREAD

**Issue by tomvantilburg** [NLeSC/3D_geospatial_risk_management#16]
What we want is to be able to do:
`select RANK() AS foo over (PARTITION BY id ORDER BY id) as foo, id from ranktest;`

**Comment by romulogoncalves** [comment]
Request submitted.

**Comment by romulogoncalves** [comment]
Instead of
select RANK() AS foo over (PARTITION BY id ORDER BY id) as foo, id from ranktest;
It should be
 select RANK() over (PARTITION BY id ORDER BY id) as foo, id from ranktest;
