### ISSUE TITLE
No 'order by' allowed in WITH clause

### ISSUE THREAD

**Issue by tomvantilburg** [NLeSC/3D_geospatial_risk_management#17]
When doing an order by inside a with clause (and prob. also a subselect) monetdb complains that this is not possible inside a 'view'.

This is blocking the option to put our points in the right order before building a geometry.

**Comment by romulogoncalves** [comment]
Request for clarification submitted.

**Comment by romulogoncalves** [comment]
It is not possible to have order by in temp tables such as the ones created by WITH clause.
Such feature it will not be possible in the near future.
