### ISSUE TITLE
Core dump on cascaded drop for pointcloud table

### ISSUE THREAD

**Issue by tomvantilburg** [NLeSC/3D_geospatial_risk_management#21]
Command:
`DROP TABLE sys."c_30fz1.laz" CASCADE;`

Result:
`./3D_geospatial_risk_management/apps/monetdb/scripts/mserver: line 67: 24321 Segmentation fault      (core dumped) $prefix/$style/$location/bin/mserver5 --set mapi_port=$port --dbinit="include geom; include sql;" --dbpath=$dbpath --set sql_logdir=$dblogs --set gdk_nr_threads=$threads $readOnly`

Manually dropping the depending merge tables works fine:
`DROP TABLE ahn3;
DROP TABLE sys."c_30fz1.laz";`

**Comment by romulogoncalves** [comment]
Fixed with:
Changeset: 60e6f41097d4 for MonetDB
URL: http://dev.monetdb.org/hg/MonetDB?cmd=changeset;node=60e6f41097d4
