### ISSUE TITLE
ST_Dump and ST_DumpPoints

### ISSUE THREAD

**Issue by romulogoncalves** [NLeSC/3D_geospatial_risk_management#32]
They should take as arguments an arbitrary list of attributes to be De-normalized with the dump.
At the moment ST_Dump only provides space for a parent id.

**Comment by tomvantilburg** [comment]
This might not be needed if #34 would be implemented.

**Comment by romulogoncalves** [comment]
#34 is solved and closed, therefore, this one can be closed.
