### ISSUE TITLE
Lateral joins for 'setof' returning function

### ISSUE THREAD

**Issue by tomvantilburg** [NLeSC/3D_geospatial_risk_management#34]
Lateral joins might solve the issue we have with ST_Dump where a table (SETOF geometry_dump) is injected in the SELECT.

See LATERAL in [(https://www.postgresql.org/docs/9.5/static/sql-select.html)]

Example:
old situation:

```
SELECT ogc_fid, ST_Dump(wkb_geometry)
FROM bgt_import2.waterdeel_2d  
LIMIT 10
```

new situation:

```
SELECT ogc_fid, dump
FROM bgt_import2.waterdeel_2d AS w  
LEFT JOIN LATERAL ST_Dump(w.wkb_geometry) as dump ON true
LIMIT 10
```

**Comment by romulogoncalves** [comment]
Features added.
Changeset: f43f1b79f22a for MonetDB
URL: http://dev.monetdb.org/hg/MonetDB?cmd=changeset;node=f43f1b79f22a
