### ISSUE TITLE
Subselect of 'Intersects' not able to handle operator

### ISSUE THREAD

**Issue by tomvantilburg** [NLeSC/3D_geospatial_risk_management#39]
Input:

```
 [ST_SetSrid(a.wkt,28992)] Intersects [b.geom]
```

Output:

```
ERROR = !TypeException:user.s44_1[24]:'geom.Intersectssubselect' undefined in:     geom.Intersectssubselect(_20:bat[:wkb],nil:BAT,X_40:wkb,false:bit);
```

**Comment by romulogoncalves** [comment]
We need more info here because I can't reproduce the issue.
Unless there is a Collect in other part of the query together with a group by.

**Comment by romulogoncalves** [comment]
All subjoin and subselect code is now in place and optimized.

Changeset: 419d44908f28 for MonetDB
URL: http://dev.monetdb.org/hg/MonetDB?cmd=changeset;node=419d44908f28

Changeset: 62d621d69ac0 for MonetDB
URL: http://dev.monetdb.org/hg/MonetDB?cmd=changeset;node=62d621d69ac0
