### ISSUE TITLE
GPU compilation fails

### ISSUE THREAD

**Issue by romulogoncalves** [NLeSC/3D_geospatial_risk_management#59]
Hi, 

@benvanwerkhoven 
When I run make in apps/gpu/pnpoly/cuda I get the following complain:
nvcc fatal   : Unsupported gpu architecture 'compute_12'

The nvcc version is:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Wed_May__4_21:01:56_CDT_2016
Cuda compilation tools, release 8.0, V8.0.26

Do I need to do set some flags or change anything in the Makefile?

**Comment by romulogoncalves** [comment]
I edited the Makefile and now the issue is more clear:
/usr/local/cuda/bin/../targets/x86_64-linux/include/host_config.h:115:2: error: #error -- unsupported GNU version! gcc versions later than 5.3 are not supported!

I need to request a gcc not older than 5.3

**Comment by benvanwerkhoven** [comment]
Hi Romulo,

Yeah, nvcc typically needs a pretty old gcc version. It depends a bit on how the machine you're using is organized. On the DAS I can just load a module for a different gcc version, for example with the command 'module load gcc/4.9.3'.

I'm not entirely sure which Makefile you're looking at at the moment, but yes normally you should specify which GPU architectures you'd expect the code will be executed on. This results a few command line options that should be passed to nvcc such as "-gencode arch=compute_35,code=sm_35" for the Tesla K20 or "-gencode arch=compute_52,code=sm_52" for the GTX Titan X. You can just specify both options to produce a binary that can run on both, at the cost of slightly increased compilation time.

Note that the code I added recently is all in the 'python' directory. I'm not that familiar with the code in the 'c' and 'cuda' directories. To me it seems that there is a lot of code there that we don't really need, most of which seems to have been copied from the CUDA SDK or something similar.

Ben

**Comment by romulogoncalves** [comment]
Hi Ben, 

Problem solved. After getting an old gcc compiler and fix few things in the Makefile in the other directories everything compiles and works. For the python directory I need to check out the kernel_tunner:
[goncalve@bricks04 python]$ make
nosetests -v
Failure: ImportError (No module named kernel_tuner) ... ERROR
Failure: ImportError (No module named kernel_tuner) ... ERROR

thanks,
Romulo

**Comment by romulogoncalves** [comment]
We are already running Contains using the GPU version of the operator.
