### ISSUE TITLE
bgt_steiger gives zero results.

### ISSUE THREAD

**Issue by romulogoncalves** [NLeSC/3D_geospatial_risk_management#68]
sql>select count(*) from bgt_kunstwerkdeel where plus_type = 'steiger';
[ 0     ]

sql>select count(*) from bgt_kunstwerkdeel;
[ 50994 ]

sql>select distinct(plus_type) from bgt_kunstwerkdeel;
[ "duiker"      ]
[ NULL  ]
[ "coupure"     ]
[ "vispassage"  ]
[ "ponton"      ]
[ "keermuur"    ]
[ "faunavoorziening"    ]
[ "overkluizing"        ]

The plus_type columns does not have values for 'steiger'

**Comment by tomvantilburg** [comment]
This may have to do with a limited dataset. Since plus-type is an optional field, not every dataprovider may have used it. For Leiden is should exist, but I'll check in the latest bgt release (ponton comes close to steiger, maybe they changed it).

**Comment by tomvantilburg** [comment]
It should be 

> bgt_type = 'steiger'

It is correct in the x3d_viewer bgt_steiger.sql

**Comment by romulogoncalves** [comment]
Indeed if we use bgt_type we have results...
