### ISSUE TITLE
bgt_road: issues in getting voetpad and driving road.

### ISSUE THREAD

**Issue by romulogoncalves** [NLeSC/3D_geospatial_risk_management#69]
This issue might be related with the support of curve_lines or incomplete data set.
Curve_lines are not supported by MonetDB geom module, therefore, the issue will not be solved.

**Comment by tomvantilburg** [comment]
Related to #71

**Comment by tomvantilburg** [comment]
Should be fixed with #65

**Comment by romulogoncalves** [comment]
When Dumping points from a Polygon we need to take the path ("<ring_id>, <point_id>") and split it into ring_id and point_id.

When making lines we should aggregate on polygon_id and ring_id so then we can triangulate them.
