### ISSUE TITLE
[Geom module]: Functionality specific to Pointcloud extension

### ISSUE THREAD

**Issue by romulogoncalves** [NLeSC/3D_geospatial_risk_management#7]
For the x3dviewer is necessary the following to convert the following functionality:

[**PC_Explode**](http://suite.opengeo.org/docs/latest/dataadmin/pointcloud/functions.html#pc-explode)
Set-returning function, converts patch into result set of one point record for each point in the patch.

[**PC_FilterEquals**](http://suite.opengeo.org/docs/latest/dataadmin/pointcloud/functions.html#pc-filterequals)
Returns a patch with only points whose values are the same as the supplied values for the requested dimension.

[**PC_Get**](http://suite.opengeo.org/docs/latest/dataadmin/pointcloud/functions.html#pc-get)
Return the numeric value of the named dimension. The dimension name must exist in the schema.

[**PC_Patch**](http://suite.opengeo.org/docs/latest/dataadmin/pointcloud/functions.html#pc-patch)
Aggregate function that collects a result set of pcpoint values into a pcpatch.

[**PC_PatchAvg**](http://suite.opengeo.org/docs/latest/dataadmin/pointcloud/functions.html#pc-patchavg)
Reads the values of the requested dimension for all points in the patch and returns the average of those values. Dimension name must exist in the schema. 
Example: SELECT PC_PatchMax(pa, 'x') FROM patches WHERE id = 7;

[**PC_PatchMin**](http://suite.opengeo.org/docs/latest/dataadmin/pointcloud/functions.html#pc-patchmin)
Reads the values of the requested dimension for all points in the patch and returns the minimum of those values. Dimension name must exist in the schema.

[**PC_Union**](http://suite.opengeo.org/docs/latest/dataadmin/pointcloud/functions.html#pc-union)
Aggregate function merges a result set of pcpatch entries into a single pcpatch.

More info about [PointCloud extension`s functions](http://suite.opengeo.org/docs/latest/dataadmin/pointcloud/functions.html)

**Comment by tomvantilburg** [comment]
All these functions are pgpointcloud specific in the sense that they deal with patches. A patch is a non-overlapping bbox with hundreds of points. Since points are stored one by one in monetdb this seems not relevant because you can use the normal filtering mechanisms for rows (eg. AVG(z) instead of AVG(PC_PatchAvg(z)) )

**Comment by romulogoncalves** [comment]
I agree, the idea was more to have documentation to show how things are translated so people in the future know how to re-write their SQL queries.

I really did not know how to label it.

**Comment by romulogoncalves** [comment]
For this, the available SQL aggregations functions on columns, X, Y and Z are enough to cover functionality.
