### ISSUE TITLE
bgt_scheiding: walls have an issue.

### ISSUE THREAD

**Issue by romulogoncalves** [NLeSC/3D_geospatial_risk_management#71]
We are not taking in consideration the curveline.
This might be the reason for some walls being missed.

**Comment by tomvantilburg** [comment]
I'll try to do an import which replaces curves with normal linestrings. postgis doesn't do a good job on curve transforming anyway

**Comment by tomvantilburg** [comment]
Should be fixed with #65

**Comment by romulogoncalves** [comment]
Solved with the new BGT load
