### ISSUE TITLE
[Geom module]: Missing functionality.

### ISSUE THREAD

**Issue by romulogoncalves** [NLeSC/3D_geospatial_risk_management#8]
PostGIS functionality missing to support x3dviewer.

[ST_AsX3D](http://postgis.net/docs/ST_AsX3D.html)
This function creates a XML to be served as input to the viewer.

[ST_Extrude](http://postgis.net/docs/ST_Extrude.html)
This method needs SFCGAL backend

[ST_MultiPolygon]()
We could use ST_BdMPolyFromText — Construct a MultiPolygon given an arbitrary collection of closed linestrings as a MultiLineString text representation Well-Known text representation. Such function is supported by MonetDB geom module.
Requires GEOS >= 2.1.0

[ST_Polygonize](http://postgis.net/docs/ST_Polygonize.html)
It is listed in MonetDB geom module
Requires GEOS >= 2.1.0.

[ST_StraightSkeleton](http://postgis.net/docs/ST_StraightSkeleton.html)
This method needs SFCGAL backend

[ST_Tesselate](http://postgis.net/docs/ST_Tesselate.html)
This method needs SFCGAL backend

[ST_Triangulate2DZ]()
This method needs SFCGAL backend

[ST_SimplifyPreserveTopology](http://postgis.net/docs/ST_SimplifyPreserveTopology.html)
It is listed in MonetDB geom module
Requires GEOS 3.0.0+

_It is implemented it needs extension to support flat table_:
[ST_DWithin](http://postgis.net/docs/ST_DWithin.html): Returns true if the geometries are within the specified distance of one another.

**Comment by romulogoncalves** [comment]
GEOS functions:
- ST_MultiPolygon: It is a type not a function. Code used in the x3dviwer below:
  " AND ST_GeometryType(a.geometrie2dgrondvlak) = 'ST_MultiPolygon' "
- ST_Polygonize added
- ST_SimplifyPreserveTopology added

**Comment by romulogoncalves** [comment]
We also need:

[ST_AsGeoJSON](http://postgis.net/docs/ST_AsGeoJSON.html)
 Return the geometry as a GeoJSON element. It will be used by common-sense viewer at NLeSC.

**Comment by romulogoncalves** [comment]
SFCGAL is now linked with MonetDB geom module thanks to Kostis.

The following functions were added:
ST_Extrude
ST_StraightSkeleton
ST_Tesselate

ST_AsX3D is the last one missing.

**Comment by tomvantilburg** [comment]
A note on sfcgal: the default build checks for the validity of the input geometry which takes a lot of resources. This can be configured at build time (though the new release might have a parameter for this at runtime)

**Comment by romulogoncalves** [comment]
The functions ST_AsX3D and ST_AsGeoJson added. They need to be heavily tested and coverage tests need to be added.

Note: All the sfcgal functions were added to the branch sfcgal. Once stable they will be merged into default.

**Comment by romulogoncalves** [comment]
Functionality added and it is already being used....
